Avoid lots of redefinition warnings but guarding the %template stuff: EPModel does "EPMODELOBJECT_TEMPLATES(Schedule, 0)" for eg
/Users/julien/Software/Others/OpenStudio3/src/epmodel/EPModel.i:30: Warning 302: Redefinition of identifier 'ScheduleVector' (Renamed from 'vector') as std::vector< openstudio::epmodel::Schedule > ignored,
/Users/julien/Software/Others/OpenStudio3/src/model/ModelCore.i:345: Warning 302: previous definition of 'ScheduleVector' (Renamed from 'vector') as std::vector< openstudio::model::Schedule >.
/Users/julien/Software/Others/OpenStudio3/src/epmodel/EPModel.i:30: Warning 302: Redefinition of identifier 'OptionalSchedule' (Renamed from 'optional') as boost::optional< openstudio::epmodel::Schedule > ignored,
/Users/julien/Software/Others/OpenStudio3/src/model/ModelCore.i:345: Warning 302: previous definition of 'OptionalSchedule' (Renamed from 'optional') as boost::optional< openstudio::model::Schedule >.